name: Post to X on Commit
on:
  push:
    branches: [ai-workout]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Post to X
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          curl -X POST "https://api.x.com/2/tweets" \
          -H "Authorization: Bearer $TWITTER_BEARER_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"text\": \"Forge Flow commit: ${{ github.event.head_commit.message }} #BuildInPublic #FitnessTech https://github.com/GordonsForge/Gym-tracker\"}"